//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePkcs7
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", ConfigurationName="ServicePkcs7.Pkcs7")]
    public interface Pkcs7
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/verifyPkcs7DetachedRequest", ReplyAction="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/verifyPkcs7DetachedResponse")]
        System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7DetachedResponse> verifyPkcs7DetachedAsync(ServicePkcs7.verifyPkcs7DetachedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/createPkcs7Request", ReplyAction="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/createPkcs7Response")]
        System.Threading.Tasks.Task<ServicePkcs7.createPkcs7Response> createPkcs7Async(ServicePkcs7.createPkcs7Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/verifyPkcs7Request", ReplyAction="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/Pkcs7/verifyPkcs7Response")]
        System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7Response> verifyPkcs7Async(ServicePkcs7.verifyPkcs7Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPkcs7DetachedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPkcs7Detached", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.verifyPkcs7DetachedRequestBody Body;
        
        public verifyPkcs7DetachedRequest()
        {
        }
        
        public verifyPkcs7DetachedRequest(ServicePkcs7.verifyPkcs7DetachedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verifyPkcs7DetachedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataB64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pkcs7B64;
        
        public verifyPkcs7DetachedRequestBody()
        {
        }
        
        public verifyPkcs7DetachedRequestBody(string dataB64, string pkcs7B64)
        {
            this.dataB64 = dataB64;
            this.pkcs7B64 = pkcs7B64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPkcs7DetachedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPkcs7DetachedResponse", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.verifyPkcs7DetachedResponseBody Body;
        
        public verifyPkcs7DetachedResponse()
        {
        }
        
        public verifyPkcs7DetachedResponse(ServicePkcs7.verifyPkcs7DetachedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verifyPkcs7DetachedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public verifyPkcs7DetachedResponseBody()
        {
        }
        
        public verifyPkcs7DetachedResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPkcs7Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPkcs7", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.createPkcs7RequestBody Body;
        
        public createPkcs7Request()
        {
        }
        
        public createPkcs7Request(ServicePkcs7.createPkcs7RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createPkcs7RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apikey;
        
        public createPkcs7RequestBody()
        {
        }
        
        public createPkcs7RequestBody(byte[] document, string apikey)
        {
            this.document = document;
            this.apikey = apikey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPkcs7Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPkcs7Response", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.createPkcs7ResponseBody Body;
        
        public createPkcs7Response()
        {
        }
        
        public createPkcs7Response(ServicePkcs7.createPkcs7ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createPkcs7ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public createPkcs7ResponseBody()
        {
        }
        
        public createPkcs7ResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPkcs7Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPkcs7", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.verifyPkcs7RequestBody Body;
        
        public verifyPkcs7Request()
        {
        }
        
        public verifyPkcs7Request(ServicePkcs7.verifyPkcs7RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verifyPkcs7RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pkcs7B64;
        
        public verifyPkcs7RequestBody()
        {
        }
        
        public verifyPkcs7RequestBody(string pkcs7B64)
        {
            this.pkcs7B64 = pkcs7B64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyPkcs7Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyPkcs7Response", Namespace="http://v1.pkcs7.plugin.server.dsv.eimzo.yt.uz/", Order=0)]
        public ServicePkcs7.verifyPkcs7ResponseBody Body;
        
        public verifyPkcs7Response()
        {
        }
        
        public verifyPkcs7Response(ServicePkcs7.verifyPkcs7ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verifyPkcs7ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public verifyPkcs7ResponseBody()
        {
        }
        
        public verifyPkcs7ResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Pkcs7Channel : ServicePkcs7.Pkcs7, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Pkcs7Client : System.ServiceModel.ClientBase<ServicePkcs7.Pkcs7>, ServicePkcs7.Pkcs7
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Pkcs7Client() : 
                base(Pkcs7Client.GetDefaultBinding(), Pkcs7Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Pkcs7Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pkcs7Client(EndpointConfiguration endpointConfiguration) : 
                base(Pkcs7Client.GetBindingForEndpoint(endpointConfiguration), Pkcs7Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pkcs7Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Pkcs7Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pkcs7Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Pkcs7Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pkcs7Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7DetachedResponse> ServicePkcs7.Pkcs7.verifyPkcs7DetachedAsync(ServicePkcs7.verifyPkcs7DetachedRequest request)
        {
            return base.Channel.verifyPkcs7DetachedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7DetachedResponse> verifyPkcs7DetachedAsync(string dataB64, string pkcs7B64)
        {
            ServicePkcs7.verifyPkcs7DetachedRequest inValue = new ServicePkcs7.verifyPkcs7DetachedRequest();
            inValue.Body = new ServicePkcs7.verifyPkcs7DetachedRequestBody();
            inValue.Body.dataB64 = dataB64;
            inValue.Body.pkcs7B64 = pkcs7B64;
            return ((ServicePkcs7.Pkcs7)(this)).verifyPkcs7DetachedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicePkcs7.createPkcs7Response> ServicePkcs7.Pkcs7.createPkcs7Async(ServicePkcs7.createPkcs7Request request)
        {
            return base.Channel.createPkcs7Async(request);
        }
        
        public System.Threading.Tasks.Task<ServicePkcs7.createPkcs7Response> createPkcs7Async(byte[] document, string apikey)
        {
            ServicePkcs7.createPkcs7Request inValue = new ServicePkcs7.createPkcs7Request();
            inValue.Body = new ServicePkcs7.createPkcs7RequestBody();
            inValue.Body.document = document;
            inValue.Body.apikey = apikey;
            return ((ServicePkcs7.Pkcs7)(this)).createPkcs7Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7Response> ServicePkcs7.Pkcs7.verifyPkcs7Async(ServicePkcs7.verifyPkcs7Request request)
        {
            return base.Channel.verifyPkcs7Async(request);
        }
        
        public System.Threading.Tasks.Task<ServicePkcs7.verifyPkcs7Response> verifyPkcs7Async(string pkcs7B64)
        {
            ServicePkcs7.verifyPkcs7Request inValue = new ServicePkcs7.verifyPkcs7Request();
            inValue.Body = new ServicePkcs7.verifyPkcs7RequestBody();
            inValue.Body.pkcs7B64 = pkcs7B64;
            return ((ServicePkcs7.Pkcs7)(this)).verifyPkcs7Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Pkcs7Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Pkcs7Port))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.122.22:9090/dsvs/pkcs7/v1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Pkcs7Client.GetBindingForEndpoint(EndpointConfiguration.Pkcs7Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Pkcs7Client.GetEndpointAddress(EndpointConfiguration.Pkcs7Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Pkcs7Port,
        }
    }
}
